replicaCount: 2

image:
  repository: docker.io/binmas/hello-wold-webserver
  tag: "1.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "hello.elicitlabs.link"  # Replace with your domain
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: websecure
  paths:
    - path: /
      pathType: Prefix
  tls:
    enabled: true
    secretName: hello-world-tls  # Created automatically by Cert-Manager

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

traefik:
  service:
    type: LoadBalancer
  additionalArguments:
    - "--metrics.prometheus=true"
    - "--entrypoints.websecure.http.tls=true"

certManager:
  email: your-email@example.com
